// SYMBOLIC.globals.c
// Generated by decompiling SYMBOLIC.COM
// using Reko decompiler version 0.10.0.0.

#include "SYMBOLIC.h"

struct seg0C00_t * g_ptrC000; // 0000C000
Eq_2128 g_t2122;
ui16 g_w2227; // 0C00:2327
Eq_2899 g_t222B;
Eq_3122 g_t222E;
word16 g_w2323; // 0C00:2423
byte g_b232C; // 0C00:242C
byte g_b2421; // 0C00:2521
cui16 g_w2423; // 0C00:2523
byte g_b2425; // 0C00:2525
byte g_b2521; // 0C00:2621
cui16 g_w2525; // 0C00:2625
Eq_895 g_t2527;
Eq_3339 g_t252A;
cui16 g_w2623; // 0C00:2723
Eq_1925 g_t2624;
byte g_b2625; // 0C00:2725
byte g_b262A; // 0C00:272A
Eq_242 g_t262C;
cui16 g_w2827; // 0C00:2927
byte g_b2829; // 0C00:2929
byte g_b2A25; // 0C00:2B25
byte g_b2B27; // 0C00:2C27
byte g_b2C25; // 0C00:2D25
cui16 g_w2C26; // 0C00:2D26
Eq_1255 g_t2C27;
Eq_2583 g_t2C5F;
cui16 g_w2D21; // 0C00:2E21
byte g_b2D40; // 0C00:2E40
Eq_2566 g_t2D5F;
byte g_b2E24; // 0C00:2F24
byte g_b2E40; // 0C00:2F40
cui16 g_w4021; // 0C00:4121
cui16 g_w4023; // 0C00:4123
Eq_2160 g_t402A;
cui16 g_w402B; // 0C00:412B
cui16 g_w402E; // 0C00:412E
byte g_b5F22; // 0C00:6022
byte g_b5F26; // 0C00:6026
Eq_866 g_t5F27;
byte g_b5F5F; // 0C00:605F
